server {
    listen 80;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Эта строка критически важна для работы React Router и модалок
        try_files $uri $uri/ /index.html;
    }

    # Кеширование картинок и webp для моментальной загрузки каталога
    location ~* \.(?:ico|css|js|gif|jpe?g|png|webp|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # Ошибка сервера
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}